name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - doc/**
      - misc/**
      - LICENSE
      - README.md
  schedule:
    - cron: 0 12 * * 5

jobs:
  test-on-vim:
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Do not run tests on Ubuntu because not enough vim runtime is prepared.
          - macos-latest
          - windows-latest

        vim_version:
          - v9.0.0000
          - v9.1.0000
          - head

        download:
          - available

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20240324
    with:
      vim_type: vim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}
